apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: fastapi-otel-eks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
        - name: fastapi
          image: 349139558431.dkr.ecr.ap-south-1.amazonaws.com/fastapi-otel-eks:latest
          ports:
            - containerPort: 80
          env:
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=fastapi,deployment.environment=eks"
